#SECRET_KEY: abcdefg123456 
SQLALCHEMY_DATABASE_URI: sqlite3://./users.db
GITHUB_CONSUMER_KEY: e6cd9f80dc198dacf09c
GITHUB_CONSUMER_SECRET: 685c42bea214bf246212d72464f457677336a2fb
DEBUG: True
UPLOAD_FOLDER: mediastore/uploads

